#lang sicp
(define (make-account balance password)
  (define (withdraw amount)
    (if (> balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "In sufficient balance!"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch password-input op)
    (if (eq? password-input password)
        (cond ((eq? op 'withdraw) withdraw)
              ((eq? op 'deposit) deposit)
              (else (error "unkown request -- MAKE-ACCOUNT" op)))
        (error "wrong password!")))
  dispatch)
