#lang sicp
(define (make-account balance password)
  (define (withdraw amount)
    (if (> balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "In sufficient balance!"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (auth-layer password-input . op)
    (cond ((null? op) (eq? password-input password))
          ((eq? password-input password) (apply dispatch op))
          (else (error "Incorrect password!"))))
  (define (dispatch op)
    (cond ((eq? op 'withdraw) withdraw)
          ((eq? op 'deposit) deposit)
          (else (error "unkown request -- MAKE-ACCOUNT" op))))
  auth-layer)
(define (make-joint acc oldpass password)
  (if (acc oldpass)
      (lambda (password-input op)
        (acc oldpass op))
      (error "Incorrect password")))
(define acc (make-account 100 'p))
(define alias (make-joint acc 'p 'a))
